name: hoornbeeck_rooster_info_app
description: This is an app that displays a schedule like roosterinfo.nl

dependencies:
  flutter:
    sdk: flutter
  shared_preferences: ^0.4.2
  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^0.1.2
  connectivity: ^0.3.1
  pull_to_refresh: ^1.1.5
  intl: ^0.15.7
  url_launcher: ^3.0.3
  cloud_firestore: ^0.8.0
  firebase_database: ^1.0.4
dev_dependencies:
  flutter_test:
    sdk: flutter


# For information on the generic Dart part of this file, see the
# following page: https://www.dartlang.org/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true
  assets:
    - assets/Resources/Videos/LogoAnimationLight.mp4
    - assets/Resources/Images/logo.png
